# Глобальні налаштування для всіх профілів
# Вимикаємо стандартну сторінку помилок Tomcat (whitelabel)
server.error.whitelabel.enabled=false
server.error.path=/error

# Дозволяємо Thymeleaf обробляти сторінки помилок
spring.thymeleaf.check-template-location=true
spring.thymeleaf.cache=false

# Логування помилок
logging.level.org.springframework.web=DEBUG
logging.level.media.toloka.rfa.config=DEBUG
