# RabbitMQ settings
#rabbitmq.host=10.4.1.12
rabbitmq.host=rfa.toloka.media
rabbitmq.virtualhost=/rfa
#rabbitmq.virtualhost=${QRFA}
rabbitmq.port=5672
rabbitmq.username=rfa
rabbitmq.password=toloka2_2018
rabbitmq.exchange=rabbitmq.exchange
rabbitmq.queue=rfa
rabbitmq.routingkey=rfa
rabbitmq.reply.timeout=60000
rabbitmq.concurrent.consumers=1
rabbitmq.max.concurrent.consumers=1

# DB parametrs
spring.datasource.url=jdbc:postgresql://rfa.toloka.media:5432/rfa
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=rfa
spring.datasource.password=toloka2_2018
#spring.jpa.show-sql=false

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
# spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
