package media.toloka.rfa.media.messanger.model.enumerate;

public enum EChatRoomType {
    CHATROOM_TYPE_PUBLIC("CHATROOM_TYPE_PUBLIC"),
    CHATROOM_TYPE_STATION("CHATROOM_TYPE_STATION"),
    CHATROOM_TYPE_PRIVATE("CHATROOM_TYPE_PRIVATE"),
    CHATROOM_TYPE_GROUP("CHATROOM_TYPE_GROUP"),
    CHATROOM_TYPE_SECURITY("CHATROOM_TYPE_SECURITY"),
    CHATROOM_TYPE_RESERV1("CHATROOM_TYPE_RESERV1"),
    CHATROOM_TYPE_RESERV2("CHATROOM_TYPE_RESERV2"),
    CHATROOM_TYPE_RESERV3("CHATROOM_TYPE_RESERV3"),
    CHATROOM_TYPE_RESERV4("CHATROOM_TYPE_RESERV4");

    public final String label;

    private EChatRoomType(String label) {
        this.label = label;
    }
}
