package media.toloka.rfa.rpc.model;

public enum ERPCJobType {
    // CONTRACT
    JOB_CONTRACT_CREATE("JOB_CONTRACT_CREATE"),
    JOB_CONTRACT_STOP("JOB_CONTRACT_STOP"),
    JOB_CONTRACT_PAUSE("JOB_CONTRACT_PAUSE"),
    JOB_CONTRACT_RESUME("JOB_CONTRACT_RESUME"),
    JOB_CONTRACT_ADD_STATION("JOB_CONTRACT_ADD_STATION"),
    JOB_CONTRACT_ADD_NAME("JOB_CONTRACT_ADD_NAME"),
    JOB_CONTRACT_MOVE_STATION("JOB_CONTRACT_MOVE_STATION"),
    // STATION
    JOB_STATION_CREATE("JOB_STATION_CREATE"),
    JOB_STATION_ALLOCATE("JOB_STATION_ALLOCATE"),
    JOB_STATION_LIBRETIME_MIGRATE("JOB_STATION_LIBRETIME_MIGRATE"),
    JOB_STATION_LIBRETIME_MIGRATE_VERSION("JOB_STATION_LIBRETIME_MIGRATE_VERSION"),
    JOB_STATION_PREPARE_NGINX("JOB_STATION_PREPARE_NGINX"),
    JOB_STATION_START("JOB_STATION_START"),
    JOB_STATION_STOP("JOB_STATION_STOP"),
    JOB_STATION_DELETE("JOB_STATION_DELETE"),
    JOB_STATION_PAUSE("JOB_STATION_PAUSE"),
    JOB_STATION_GET_STATISTIC("JOB_STATION_GET_STATISTIC"),
    JOB_STATION_GET_STATUS("JOB_STATION_GET_STATUS"),
    JOB_STATION_GET_PS("JOB_STATION_GET_PS"),
    JOB_STATION_ENABLE("JOB_STATION_ENABLE"),
    JOB_STATION_DISABLE("JOB_STATION_DISABLE"),
    JOB_STATION_SETPASSWORD("JOB_STATION_SETPASSWORD"),
    PODCAST_FROM_RSS_LOAD("PODCAST_FROM_RSS_LOAD"), // завантажуємо подкаст. Це довга операція і тому результат непередбачуваний.
    JOB_TTS("JOB_TTS"), // TTS перетворення тексту в голос
    JOB_TTS_FILES_READY("JOB_TTS_FILES_READY"), // TTS відпрацювало, можна забирати файли
    JOB_STT("JOB_STT"), // TTS перетворення голосу в текст
    JOB_STT_FILES_READY("JOB_STT_FILES_READY"), // STT відпрацювало, можна забирати файли
    JOB_GETRUNSTATIOM("JOB_GETRUNSTATIOM"); // Беремо з сервера перелік станцій, які працюють в цей момент

    public final String label;

    private ERPCJobType(String label) {
        this.label = label;
    }
}
